[tool.briefcase]
project_name = "MyCartable"
bundle = "coding.cacahuete"
version = "1.3.2"
url = "https://github.com/jgirardet/MyCartable"
license = "GNU General Public License v3 (GPLv3)"
author = 'Jimmy Girardet'
author_email = "ijkl@netc.fr"

[tool.briefcase.app.mycartable]
formal_name = "MyCartable"
description = "L'école sur ordinateur, tout un un !!!"
icon = "src/data/icons/mycartable"
installer_icon = "src/data/icons/mycartable"
sources = ['src/mycartable']
requires = ['pyqt5==5.15.2',
            'pony>=0.7.11,<0.8',
            'Pillow==7.1.2',
            'mako==1.1.2',
            'beautifulsoup4',
            'loguru',
            "PyMuPDF==1.17.6",
            "packaging",
            "emoji-country-flag>=1.2.3,<2"
            ]


[tool.briefcase.app.mycartable.macOS]
requires = []

[tool.briefcase.app.mycartable.linux]
requires = []
system_requires = []

[tool.briefcase.app.mycartable.windows]
requires = []

# Mobile deployments
[tool.briefcase.app.mycartable.iOS]
requires = []

[tool.briefcase.app.mycartable.android]
requires = []
