# def test_bla():
#     assert [
#         {
#             "id": 1,
#             "nom": "Leçons",
#             "famille": 0,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 10,
#                     "titre": "letitre 0 3",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 7,
#                     "titre": "letitre 0 2",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 4,
#                     "titre": "letitre 0 1",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 1,
#                     "titre": "letitre 0 0",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#             ],
#         },
#         {
#             "id": 2,
#             "nom": "Exercices",
#             "famille": 1,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 11,
#                     "titre": "letitre 1 3",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 8,
#                     "titre": "letitre 1 2",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 5,
#                     "titre": "letitre 1 1",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 2,
#                     "titre": "letitre 1 0",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#             ],
#         },
#         {
#             "id": 3,
#             "nom": "Evaluations",
#             "famille": 2,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 12,
#                     "titre": "letitre 2 3",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 9,
#                     "titre": "letitre 2 2",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 6,
#                     "titre": "letitre 2 1",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 3,
#                     "titre": "letitre 2 0",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#             ],
#         },
#     ] == [
#         {
#             "id": 1,
#             "nom": "Le�ons",
#             "famille": 0,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 10,
#                     "titre": "letitre 0 3",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 7,
#                     "titre": "letitre 0 2",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 4,
#                     "titre": "letitre 0 1",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#                 {
#                     "id": 1,
#                     "titre": "letitre 0 0",
#                     "activite": 1,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 0,
#                 },
#             ],
#         },
#         {
#             "id": 2,
#             "nom": "Exercices",
#             "famille": 1,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 11,
#                     "titre": "letitre 1 3",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 8,
#                     "titre": "letitre 1 2",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 5,
#                     "titre": "letitre 1 1",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#                 {
#                     "id": 2,
#                     "titre": "letitre 1 0",
#                     "activite": 2,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 1,
#                 },
#             ],
#         },
#         {
#             "id": 3,
#             "nom": "Evaluations",
#             "famille": 2,
#             "matiere": 1,
#             "pages": [
#                 {
#                     "id": 12,
#                     "titre": "letitre 2 3",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 9,
#                     "titre": "letitre 2 2",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 6,
#                     "titre": "letitre 2 1",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#                 {
#                     "id": 3,
#                     "titre": "letitre 2 0",
#                     "activite": 3,
#                     "lastPosition": None,
#                     "matiere": 1,
#                     "matiereNom": "Math",
#                     "famille": 2,
#                 },
#             ],
#         },
#     ]
